### ISSUE TITLE
Reset button not resetting text search and checkboxes

### ISSUE THREAD

**Issue by jengalas** [derekeder/FusionTable-Map-Template#47]
I've recently been working with the new version of the template, which is perfect for my purposes except that the reset button doesn't seem to work as before.

This page is running the older version of the template:

http://surveymarks.planetzhanna.com/fusiontables/beacons/

Here, if you uncheck some of the checkboxes and then hit reset, the checkboxes are restored to their checked state, as expected. Similarly, if you do a text search (say, "ly") in the PID box and then reset, the "ly" is cleared and the hint text is restored to the box.

In the new version, here:

http://surveymarks.planetzhanna.com/fusiontables/beacons/updated/

the reset button does not reset the text or the "checked" state, although it does still reset the marker display and the number of results.

**Comment by jengalas** [comment]
I've posted the code here:

[index.html](https://gist.github.com/jengalas/b0595905f800a3d1f72f)

[maps_lib.js](https://gist.github.com/jengalas/a685c1d63ad0ef49930d)

**Comment by derekeder** [comment]
@jengalas thanks for reporting this. I just pushed up a fix that addresses this issue. Let me know if it works for you!

**Comment by jengalas** [comment]
Looks perfect so far! Thank you!
