### ISSUE TITLE
Icon legend?

### ISSUE THREAD

**Issue by gdwhite** [derekeder/FusionTable-Map-Template#56]
Hi Derek,
I was wondering if there's an easy way to include icon legends. I realize that this may be a function of Fusion Tables as opposed to your template but I thought I would ask just in case.

Thanks!

**Comment by derekeder** [comment]
@gdwhite could you provide an example of what you'd like it to look like? 

Also, Fusion Tables does provide a way to make your own legend, but it is not supported by this template and may not look the way you want: https://developers.google.com/fusiontables/docs/samples/legend
