### ISSUE TITLE
Maps API Key warning

### ISSUE THREAD

**Issue by shua123** [derekeder/FusionTable-Map-Template#57]
Google Maps API now returns a warning if you don't include the API key in the Maps API script call. At the moment it does not affect functionality.

Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
![image](https://cloud.githubusercontent.com/assets/1593537/15166936/79a38ade-16e9-11e6-823e-273ca08e5fea.png)

Reference links:
https://developers.google.com/maps/documentation/javascript/get-api-key
http://stackoverflow.com/questions/35890582/google-maps-api-warning-noapikeys

**Comment by derekeder** [comment]
Thanks @shua123. We have API keys as a requirement of using this template. Do you think this change on Google's end will require any changes to the template?

**Comment by shua123** [comment]
So the change in the template would be to include the API key in this line: https://github.com/derekeder/FusionTable-Map-Template/blob/master/index.html#L109

similar to the example [here](https://developers.google.com/maps/documentation/javascript/get-api-key#types-of-api-keys):
`  <script async defer src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap"
  type="text/javascript"></script>`

**Comment by derekeder** [comment]
ok readme updated. kind of annoying you have to set it right in the script tag, but it looks like the only way to do it.
