### ISSUE TITLE
Ideas for text/table display for the visually impaired?

### ISSUE THREAD

**Issue by smach** [derekeder/FusionTable-Map-Template#60]
Hi Derek. Thanks for sharing the template, it's great. I was wondering if you might have any ideas for outputting a table of affected polygons along with the actual map, based on this comment I received from a user of the [Competitive Congressional Districts Near You](http://www.machlis.com/elections/CongressionalDistricts/) Web app that I built with your template:

> Is there any way your congressional districts app could output a text list of nearby districts and color equivalents? I am totally blind, so the map does me no good. Completely understand if this is impractical or impossible, but figured I'd ask.

Update: I saw the results list where you can display _points_ within the radius, but I'm not quite sure whether it's possible to modify that to show _polygons_ within the radius, not just points. If you have any suggestions for me, that would be most welcome!

**Comment by derekeder** [comment]
@smach yes, it is possible to show a list of polygons. You can follow the instructions here: https://github.com/derekeder/FusionTable-Map-Template/wiki/List-search-results

**Comment by smach** [comment]
OK sorry, I was playing around with that last night and thought it was to show a list of points within the radius, not a list of polygons that intersect the radius, since none of my polygons were showing up. Clearly I did something wrong. I will look in more detail over the weekend. Thank you!

**Comment by derekeder** [comment]
ok great!
